from __future__ import annotations

from pathlib import Path

from packages.core.models import Certificate, ParsedDocument
from packages.core.security import PROTOTYPE_SECURITY_NOTICE


def build_rocrate_metadata(
    document: ParsedDocument,
    certificate: Certificate,
    bundle_id: str,
    *,
    has_build_provenance: bool = False,
    has_release_manifest: bool = False,
    has_release_signature: bool = False,
    has_release_verification: bool = False,
    has_release_public_key: bool = False,
    has_execution_plan: bool = False,
    has_execution_attempts: bool = False,
    has_execution_receipts: bool = False,
    has_execution_stub_outputs: bool = False,
    has_repository_metadata: bool = False,
    has_reference_audit: bool = False,
    has_reference_resolution: bool = False,
    has_artifact_bindings: bool = False,
    has_transparency_record: bool = False,
    has_transparency_checkpoint: bool = False,
    has_verification_receipts: bool = False,
    has_witness_record: bool = False,
    has_witness_checkpoint: bool = False,
    has_published_checkpoint_reference: bool = False,
    original_artifact_name: str | None = None,
) -> dict:
    root_id = './'
    has_part = [
        {'@id': 'document.txt'},
        {'@id': 'certificate.json'},
        {'@id': 'report.html'},
        {'@id': 'manifest.json'},
        {'@id': 'attestation.json'},
    ]
    graph = [
        {
            '@id': 'ro-crate-metadata.json',
            '@type': 'CreativeWork',
            'about': {'@id': root_id},
            'conformsTo': {'@id': 'https://w3id.org/ro/crate/1.1'},
        },
        {
            '@id': root_id,
            '@type': 'Dataset',
            'name': f'Audit-Proof bundle {bundle_id}',
            'description': 'Machine-readable audit certificate bundle generated by Audit-Proof PoC.',
            'securityNotice': PROTOTYPE_SECURITY_NOTICE,
            'hasPart': has_part,
        },
        {
            '@id': 'document.txt',
            '@type': 'File',
            'name': document.source_name or 'document.txt',
            'encodingFormat': 'text/plain',
            'sha256': document.doc_hash,
        },
        {
            '@id': 'certificate.json',
            '@type': 'File',
            'name': 'Audit certificate',
            'encodingFormat': 'application/json',
            'sha256': certificate.cert_hash,
        },
        {
            '@id': 'report.html',
            '@type': 'File',
            'name': 'Human-readable audit report',
            'encodingFormat': 'text/html',
        },
        {
            '@id': 'manifest.json',
            '@type': 'File',
            'name': 'Bundle manifest',
            'encodingFormat': 'application/json',
        },
        {
            '@id': 'attestation.json',
            '@type': 'File',
            'name': 'Bundle attestation',
            'encodingFormat': 'application/json',
        },
        {
            '@id': '#document',
            '@type': 'ScholarlyArticle',
            'name': document.title or document.source_name or 'Untitled document',
            'identifier': document.metadata.get('doi') or document.doc_hash,
        },
        {
            '@id': '#certificate',
            '@type': 'CreativeWork',
            'name': 'Audit-Proof certificate',
            'about': {'@id': '#document'},
            'version': certificate.certificate_version,
            'dateCreated': certificate.timestamp.isoformat(),
            'keywords': [certificate.domain, certificate.tier, certificate.provenance.policy_version, certificate.issuance.status],
            'securityNotice': certificate.security_notice,
        },
    ]


    if has_release_manifest:
        has_part.append({'@id': 'release_manifest.json'})
        graph.append({
            '@id': 'release_manifest.json',
            '@type': 'File',
            'name': 'Source release manifest',
            'encodingFormat': 'application/json',
        })
    if has_release_signature:
        has_part.append({'@id': 'release_manifest.signature.json'})
        graph.append({
            '@id': 'release_manifest.signature.json',
            '@type': 'File',
            'name': 'Release manifest signature',
            'encodingFormat': 'application/json',
        })
    if has_release_verification:
        has_part.append({'@id': 'release_verification.json'})
        graph.append({
            '@id': 'release_verification.json',
            '@type': 'File',
            'name': 'Release verification record',
            'encodingFormat': 'application/json',
        })
    if has_release_public_key:
        has_part.append({'@id': 'keys/release_signing_public_key.pem'})
        graph.append({
            '@id': 'keys/release_signing_public_key.pem',
            '@type': 'File',
            'name': 'Release signing public key',
            'encodingFormat': 'application/x-pem-file',
        })

    if has_build_provenance:
        has_part.append({'@id': 'build_provenance.json'})
        graph.append(
            {
                '@id': 'build_provenance.json',
                '@type': 'File',
                'name': 'Build provenance',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_execution_plan:
        has_part.append({'@id': 'execution_plan.json'})
        graph.append(
            {
                '@id': 'execution_plan.json',
                '@type': 'File',
                'name': 'Execution preflight plan',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_execution_attempts:
        has_part.append({'@id': 'execution_attempts.json'})
        graph.append(
            {
                '@id': 'execution_attempts.json',
                '@type': 'File',
                'name': 'Execution attempt log (stub)',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_execution_receipts:
        has_part.append({'@id': 'execution_receipts.json'})
        graph.append(
            {
                '@id': 'execution_receipts.json',
                '@type': 'File',
                'name': 'Execution receipt log (dry-run stub)',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_execution_stub_outputs:
        has_part.append({'@id': 'execution_stub_outputs.json'})
        graph.append(
            {
                '@id': 'execution_stub_outputs.json',
                '@type': 'File',
                'name': 'Execution stub outputs',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_repository_metadata:
        has_part.append({'@id': 'repository_metadata.json'})
        graph.append(
            {
                '@id': 'repository_metadata.json',
                '@type': 'File',
                'name': 'Repository metadata enrichment',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_reference_resolution:
        has_part.append({'@id': 'reference_resolution.json'})
        graph.append(
            {
                '@id': 'reference_resolution.json',
                '@type': 'File',
                'name': 'Reference DOI resolution audit',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_artifact_bindings:
        has_part.append({'@id': 'artifact_bindings.json'})
        graph.append(
            {
                '@id': 'artifact_bindings.json',
                '@type': 'File',
                'name': 'Artifact hash bindings',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_transparency_record:
        has_part.append({'@id': 'transparency_record.json'})
        graph.append(
            {
                '@id': 'transparency_record.json',
                '@type': 'File',
                'name': 'Transparency log inclusion record snapshot',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_transparency_checkpoint:
        has_part.append({'@id': 'transparency_checkpoint_snapshot.json'})
        graph.append(
            {
                '@id': 'transparency_checkpoint_snapshot.json',
                '@type': 'File',
                'name': 'Transparency checkpoint snapshot',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_verification_receipts:
        has_part.append({'@id': 'verification_receipts.json'})
        graph.append(
            {
                '@id': 'verification_receipts.json',
                '@type': 'File',
                'name': 'Multi-verifier receipts',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_witness_record:
        has_part.append({'@id': 'witness_record.json'})
        graph.append(
            {
                '@id': 'witness_record.json',
                '@type': 'File',
                'name': 'Witness log inclusion record snapshot',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_witness_checkpoint:
        has_part.append({'@id': 'witness_checkpoint_snapshot.json'})
        graph.append(
            {
                '@id': 'witness_checkpoint_snapshot.json',
                '@type': 'File',
                'name': 'Witness checkpoint snapshot',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if has_published_checkpoint_reference:
        has_part.append({'@id': 'published_checkpoint_reference.json'})
        graph.append(
            {
                '@id': 'published_checkpoint_reference.json',
                '@type': 'File',
                'name': 'Published checkpoint reference',
                'encodingFormat': 'application/json',
                'about': {'@id': '#certificate'},
            }
        )

    if original_artifact_name:
        has_part.append({'@id': original_artifact_name})
        graph.append(
            {
                '@id': original_artifact_name,
                '@type': 'File',
                'name': f'Original upload: {original_artifact_name}',
                'encodingFormat': 'application/octet-stream',
                'about': {'@id': '#document'},
            }
        )

    return {
        '@context': 'https://w3id.org/ro/crate/1.1/context',
        '@graph': graph,
    }


def write_rocrate(bundle_dir: str | Path, metadata: dict) -> Path:
    import json

    bundle_path = Path(bundle_dir)
    out = bundle_path / 'ro-crate-metadata.json'
    out.write_text(json.dumps(metadata, indent=2), encoding='utf-8')
    return out
